#!/bin/bash
# STOP! Before going any further, think: are you going to regret the decision
# to write this script?
#     Deciding to write this in bash was not one of my better decisions.
#     -- https://twitter.com/alex_gaynor/status/369892494114164736

IFS="`printf "\n\t"`"
set -eu
cd "$(dirname "$0")"

if [[ "$(git status -s | wc -l)" -gt 0 ]]; then
    echo "ERROR: Stash uncommitted changes first:"
    git status -s
    exit 1
fi

cleanup() {
    git reset --hard
    git checkout master
    git branch -D temp || true
}
trap cleanup EXIT

git branch -D temp || true
git checkout -b temp
npm run build
cp example.html index.html
git add -f index.html dist/
git commit -am "Build for gh-pages"
git push -f origin HEAD:gh-pages
